[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.20"
optimizer = true
optimizer_runs = 200
via_ir = true
verbosity = 2
fuzz = { runs = 256 }
invariant = { runs = 256, depth = 15, fail_on_revert = false, call_override = false }
fs_permissions = [{ access = "read", path = "./" }]

# Remappings
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@layerzero/=lib/layerzero-contracts/",
    "forge-std/=lib/forge-std/src/",
    "@test/=test/"
]

# Rootstock network configuration
[rpc_endpoints]
rootstock_mainnet = "https://public-node.rsk.co"
rootstock_testnet = "https://public-node.testnet.rsk.co"